<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>Devlooped.Spectre.Yaml</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NuGetizer" Version="1.4.7" />
    <PackageReference Include="Spectre.Console" Version="0.50.0" />
    <PackageReference Include="YamlDotNet" Version="16.3.0" />
  </ItemGroup>
</Project>